language: php
php:
  - 7.1
mysql:
  database: activecollab_promises_test
  username: root
  encoding: utf8mb4
install: composer install --dev
before_script:
  # create the database
  - mysql -e 'create database if not exists activecollab_promises_test;'
script: phpunit -c test/phpunit.xml
